### ISSUE TITLE
✨ Feat: Project Scaffold

### ISSUE THREAD

**Issue by gli-ryan-kwon** [gli-ryan-kwon/example-api#1]
### ✨ Task Title

Set up basic example features for nestjs app.

### ⚙ Task Content

- [x] : Write README including a test coverage
- [x] : Create an example resource Cat with CRUD
- [x] : Connect MongoDB with Mongoose ODM
